### ISSUE TITLE
strapi-plugin-rest-cache development state

### ISSUE THREAD

**Issue by jonathanzO** [strapi-community/strapi-plugin-rest-cache#42]
Hi there, 
I've read the readme and was just wondering if is this plugin still considered Alpha in terms of state, can this can be used in Production

Thanks

**Comment by stafyniaksacha** [comment]
The core of this plugin is stable and used in production on many deployed strapi, so yes you can use this in yours!

The services API won't change since I do not have time to maintains this plugin. 
The admin side would need a refresh (nothing serious has been made, everything could be trash).

I can still do review / release if someone send a pull requests!

**Comment by derrickmehaffy** [comment]
Will set this as closed as even if @stafyniaksacha doesn't have time to maintain it, us others in the org can pick some things up (and I am working on a few things)
